Dynamix/create pole zero
dsp-work/filter_param pull request #53
Opened 2021-10-10 04:49 UTC by 9071-dynamix

極零配置

2021-10-11 13:00 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +vector<complex<double>> FilterParam::tprint_pz_se(const vector<double>& coef) const
```suggestion
vector<complex<double>> FilterParam::tprint_pz_se(const vector<double>& coef, const string& filename) const
```

2021-10-11 13:00 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +vector<complex<double>> FilterParam::tprint_pz_se(const vector<double>& coef) const
直接関係ないですが、これが済んだら`gprint`も作成しましょう

2021-10-11 13:02 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +}
これvoidじゃないのに、リターンないけど....

2021-10-11 13:03 UTC, chatblanc-ciel commented on main.cpp
> +}
ここ新規追加になってるの謎
rebaseが済んでないのかな？

2021-10-13 09:44 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			zero_func = &FilterParam::tprint_zero_even;
`tprint`しちゃだめでしょう。
```
vector<complex<double>> pole_even()
```

2021-10-14 15:04 UTC, chatblanc-ciel commented on .gitignore
> +.vscode
```suggestion
.vscode
```

2021-10-14 15:06 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	}
ここで複素共役も取ってあげれば、ループ一個ですむよ

2021-10-14 15:06 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +		pole_value.reserve(m_order);
```suggestion
		pole_value.reserve(2*m_order);
```

2021-10-14 15:07 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +		pole_value.reserve(m_order);
```suggestion
		pole_value.reserve(2*m_order + 1);
```

2021-10-19 08:18 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	vector<complex<double>> pole_value;
```suggestion
	vector<complex<double>> pole;
```

2021-11-06 09:38 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +		}
出現頻度順に変更
複素＞実数解＞重解

2021-11-06 09:39 UTC, chatblanc-ciel commented
check list

- [ ] pole odd
- [ ] pole even
- [ ] zero odd
- [ ] zero even

2021-11-11 02:02 UTC, chatblanc-ciel requested changes

2021-11-11 02:02 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	const double acc = 1.0e-10;
```suggestion
	const double acc = 1.0e-10;

	std::vector<complex<double>> pole;
		pole.reserve(2*m_order);
```

2021-11-11 02:02 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			complex<double> minus_pole(0.5*(-coef.at(m) - sqrt(disc)), 0.0);
```suggestion
                        double disc_sqrt = sqrt(disc);
			complex<double> plus_pole(0.5*(-coef.at(m) + sqrt(disc)), 0.0);
			complex<double> minus_pole(0.5*(-coef.at(m) - sqrt(disc)), 0.0);
```

2021-11-15 13:22 UTC, chatblanc-ciel requested changes

2021-11-15 13:22 UTC, chatblanc-ciel commented on lib/filter_param.cpp
>  			freq_res_func = &FilterParam::freq_res_se;
更新のため

2021-11-18 10:00 UTC, 9071-dynamix commented on lib/filter_param.cpp
>  			freq_res_func = &FilterParam::freq_res_se;
すみません、意図が掴めないのですがこれはなにをしたいのかもう少し詳しく説明してほしいです

2021-11-21 20:27 UTC, chatblanc-ciel requested changes

2021-11-21 20:27 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +	const double acc = 1.0e-10;
なんのためのパラメータかコメント欲しい

2021-11-21 20:27 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			pole.emplace_back(minus_pole);
poleに直接入れて、pole.back().conj()をさらにemplaceしよう

2021-11-21 20:27 UTC, chatblanc-ciel commented on main.cpp
> +	std::vector<complex<double>> pole2;
pole1、2だと違いがわかりにくいから、変数名で用途が察せるようにしたい

2021-11-21 20:27 UTC, chatblanc-ciel commented on main.cpp
> +		assert(std::round(pole_res.at(n).real()*abc) == std::round(pole2.at(n).real()*abc));
虚部のチェックいらないの？

2021-11-21 20:27 UTC, chatblanc-ciel commented on main.cpp
> +	const unsigned int abc = 1000;		// 10^-n(小数点以下n桁)まで精度を検査
abcってなんじゃらほい？

2021-11-26 08:20 UTC, chatblanc-ciel requested changes

2021-11-26 08:20 UTC, chatblanc-ciel commented on lib/filter_param.cpp
> +			pole.emplace_back(minus_pole);
ここ変わってなくない？

2022-04-19 17:56 UTC, closed without merging